- hosts: web
  become: true
  tasks:
    - name: Install Node.js and Nginx
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - nodejs
        - nginx

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Start the Node.js application
      command: pm2 start /home/ec2-user/chat-app/app.js --name chat-app -f
      ignore_errors: yes
      register: pm2_start_result

    - name: Ensure pm2 process is running
      command: pm2 start /home/ec2-user/chat-app/app.js --name chat-app
      when: pm2_start_result.rc != 0  # Check the return code of the previous command
